#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

FINAL_STATUSES = {"covered", "merged", "index-only", "intentionally-omitted"}
INCOMPLETE_STATUSES = {"", "unread", "blocked"}
ALL_STATUSES = FINAL_STATUSES | INCOMPLETE_STATUSES
REQUIRES_TARGET_PAGES = {"covered", "merged", "index-only"}
TABLE_SEPARATOR_RE = re.compile(r"^:?-{3,}:?$")


def load_manifest(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("manifest.json must contain a list of entries")
    return data


def split_markdown_table_row(line: str) -> list[str] | None:
    stripped = line.strip()
    if not stripped.startswith("|"):
        return None
    body = stripped[1:-1] if stripped.endswith("|") else stripped[1:]
    cells: list[str] = []
    current: list[str] = []
    escaped = False
    for char in body:
        if escaped:
            current.append(char)
            escaped = False
            continue
        if char == "\\":
            escaped = True
            continue
        if char == "|":
            cells.append("".join(current).strip())
            current = []
            continue
        current.append(char)
    if escaped:
        current.append("\\")
    cells.append("".join(current).strip())
    return cells


def is_separator_row(cells: list[str]) -> bool:
    return bool(cells) and all(TABLE_SEPARATOR_RE.fullmatch(cell) for cell in cells)


def parse_coverage_table(path: Path) -> list[dict[str, str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    header_index = next(
        (
            idx
            for idx, line in enumerate(lines)
            if (cells := split_markdown_table_row(line))
            and [cell.lower() for cell in cells][:8]
            == ["index", "file", "title", "lines", "words", "status", "target pages", "notes"]
        ),
        None,
    )
    if header_index is None or header_index + 1 >= len(lines):
        raise ValueError(
            "coverage-map.md is missing the expected markdown table header"
        )

    header_cells = split_markdown_table_row(lines[header_index])
    if not header_cells:
        raise ValueError("coverage-map.md header row could not be parsed")
    headers = [cell.strip().lower() for cell in header_cells]
    rows: list[dict[str, str]] = []
    for line in lines[header_index + 1 :]:
        cells = split_markdown_table_row(line)
        if cells is None:
            if rows:
                break
            continue
        if is_separator_row(cells):
            continue
        if len(cells) != len(headers):
            raise ValueError(f"Malformed coverage row: {line}")
        rows.append(dict(zip(headers, cells)))
    return rows


def validate_coverage(
    manifest: list[dict], coverage_rows: list[dict[str, str]]
) -> list[str]:
    problems: list[str] = []
    manifest_by_file = {item["file"]: item for item in manifest}
    coverage_by_file = {row.get("file", ""): row for row in coverage_rows}

    missing_files = [file for file in manifest_by_file if file not in coverage_by_file]
    extra_files = [file for file in coverage_by_file if file not in manifest_by_file]

    for file in missing_files:
        problems.append(f"Missing coverage row for manifest file: {file}")
    for file in extra_files:
        problems.append(f"Coverage row references unknown file: {file}")

    for file, row in coverage_by_file.items():
        if file not in manifest_by_file:
            continue
        status = row.get("status", "").strip()
        target_pages = row.get("target pages", "").strip()
        notes = row.get("notes", "").strip()

        if status not in ALL_STATUSES:
            problems.append(f"{file}: unknown status '{status}'")
            continue
        if status in INCOMPLETE_STATUSES:
            problems.append(
                f"{file}: status is still incomplete ('{status or 'blank'}')"
            )
            continue
        if status in REQUIRES_TARGET_PAGES and not target_pages:
            problems.append(f"{file}: status '{status}' requires target pages")
        if status == "intentionally-omitted" and not notes:
            problems.append(
                f"{file}: intentionally-omitted requires an explanatory note"
            )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify that every source chunk has a final coverage status before an ingest is declared complete."
    )
    parser.add_argument(
        "--manifest",
        required=True,
        help="Path to manifest.json generated by split_markdown.py",
    )
    parser.add_argument(
        "--coverage",
        required=True,
        help="Path to coverage-map.md whose rows have been filled with final statuses",
    )
    args = parser.parse_args()

    manifest = load_manifest(Path(args.manifest))
    coverage_rows = parse_coverage_table(Path(args.coverage))
    problems = validate_coverage(manifest, coverage_rows)

    if problems:
        print("Coverage verification failed:")
        for problem in problems:
            print(f"- {problem}")
        return 1

    print(
        json.dumps(
            {
                "manifest_entries": len(manifest),
                "coverage_rows": len(coverage_rows),
                "status": "complete",
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
